---
- name: file play
  hosts: localhost
  tasks:
    - name: something
      file:
        state: touch # dict(type='str', choices=['absent', 'directory', 'file', 'hard', 'link', 'touch']),
        path: /home/paul/testfile-path.txt # dict(type='path', required=True, aliases=['dest', 'name']),
        recurse: False # =dict(type='bool', default=False),
        force: False # dict(type='bool', default=False),  # Note: Should not be in file_common_args in future
        follow: True # dict(type='bool', default=True),  # Note: Different default than file_common_args
        #src: # dict(type='path'),  # Note: Should not be in file_common_args in future
        # modification_time: # dict(type='str'),
        # modification_time_format: # dict(type='str', default='%Y%m%d%H%M.%S'),
        # access_time: # dict(type='str'),
        # access_time_format: # dict(type='str', default='%Y%m%d%H%M.%S'),

